### Get all products
GET http://localhost:4000/api/products

###

POST http://localhost:4000/api/product
Content-Type: application/json

{
  "name": 123,
  "description": "Matbord med 15 plåtben",
  "price": 2979,
  "imageId": "11111111111",
  "stock": 1123123,
  "categories": 2
}

### Get one product

GET http://localhost:4000/api/products/628f408b21bbf42102dc7a22

### Get all products of one category

GET http://localhost:4000/api/products/category/stol


### Update product
PUT http://localhost:4000/api/products/628f408b21bbf42102dc7a24
Content-Type: application/json

{
  "name": 444444,
  "description": "en röd stol",
  "price": 299,
  "imageId": "628b7030d071e31e672871b4",
  "stock": 200,
  "categories": ["stol", "trä"]
}

### Delete product
DELETE http://localhost:4000/api/products/628f408b21bbf42102dc7a22
