GET http://localhost:4000/api/users

###

GET http://localhost:4000/api/user/628b815b1ee6608822f08c21

###

POST http://localhost:4000/api/user
Content-Type: application/json

{

  "firstname": "Lina",
  "lastname": "Linas",
  "password": "123",
  "email": "hej@hej.com"

}

###

PUT http://localhost:4000/api/user/628792ccdd2e580d8d820450
Content-Type: application/json

{
  "firstname": "Badiba",
  "lastname": "Badoba",
  "password": "123",
  "email": "hej@hej.com"
}

###

DELETE http://localhost:4000/api/user/628792ccdd2e580d8d820450