GET http://localhost:4000/api/users

###

GET http://localhost:4000/api/loggedin

###

GET http://localhost:4000/api/user/628b815b1ee6608822f08c21

###

POST http://localhost:4000/api/user
Content-Type: application/json

{
  "email": "lii@lii.com",
  "password": "123123",
  "isAdmin": true
}

###

POST http://localhost:4000/api/login
Content-Type: application/json

{
  "email": "lii@lii.com",
  "password": "123"
}

### 

PUT http://localhost:4000/api/user/628ded258bfd9f9bd9e5902a
Content-Type: application/json

{
  "email": "lii@lii.com",
  "password": "123",
  "isAdmin": true
}

###

DELETE http://localhost:4000/api/user/628792ccdd2e580d8d820450

###

DELETE http://localhost:4000/api/logout