GET http://localhost:4000/api/shipper

###

GET http://localhost:4000/api/shipper/62875028ad3688cf640d2168

###

POST http://localhost:4000/api/shipper
Content-Type: application/json

{
  "shipper": "InstaBox",
  "cost": "0",
  "deliveryDays": "3"
}

###

DELETE http://localhost:4000/api/shipper/62875028ad3688cf640d2168
