
### Get all orders
GET http://localhost:4000/api/orders

### Get one order

GET http://localhost:4000/api/order/629622394f44ab171a366220

### Create new order

POST http://localhost:4000/api/order
Content-Type: application/json

{
  "customer": "629606accf491f5114db445f",
  "products": [
    {
      "name": "Wonderwoman",
      "description": "Diana's truthful and equal NFT.",
      "price": 12,
      "imageId": "/assets/images/Products/DCNFT/WonderWomanDCNFT.png",
      "stock": 9,
      "categories": [
        "DC",
        "Inanimate"
      ],
      "_id": "6295d2f68c6ba2e1364a6a3b"
    }
  ],
  "shipper": {
    "cost": 10,
    "deliveryDays": 1,
    "shipper": "Postnord",
    "_id":"6297675967d55a01e86868d3"
    },
  "deliveryAddress": [
    {
      "fullname": "Linnea Albertsson",
      "street": "Runiusgatan 7",
      "zipcode": 41653,
      "city": "Göteborg",
      "_id": "6297675967d55a01e86868d4"
    }
  ],
  "isSent": false,
  "paymentMethod": "Swish",
  "totalPrice": 108
}

### Update order

PUT http://localhost:4000/api/order/6298741568c3147a061a5593
Content-Type: application/json

{
  "_id": "6298741568c3147a061a5593",
  "customer": "629606accf491f5114db445f",
  "products": [
    {
      "name": "Wonderwoman",
      "description": "Diana's truthful and equal NFT.",
      "price": 12,
      "imageId": "/assets/images/Products/DCNFT/WonderWomanDCNFT.png",
      "stock": 9,
      "categories": [
        "DC",
        "Inanimate"
      ],
      "_id": "6295d2f68c6ba2e1364a6a3b"
    }
  ],
  "shipper": {
    "cost": 10,
    "deliveryDays": 1,
    "shipper": "Postnord",
    "_id":"6297675967d55a01e86868d3"
    },
  "deliveryAddress": [
    {
      "fullname": "Linnea Albertsson",
      "street": "Runiusgatan 7",
      "zipcode": 41653,
      "city": "Göteborg",
      "_id": "6297675967d55a01e86868d4"
    }
  ],
  "isSent": false,
  "paymentMethod": "Swish",
  "totalPrice": 108
}

### Delete order

DELETE http://localhost:4000/api/order/628785d71fbd71f9fc387d08